apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance-tracker

resources:
  - namespace.yaml
  - pvc.yaml
  - server-deployment.yaml
  - client-deployment.yaml
  - services.yaml
  - gateway.yaml

commonLabels:
  app.kubernetes.io/name: finance-tracker
  app.kubernetes.io/managed-by: kustomize
