apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-tracker-data
  namespace: finance-tracker
  labels:
    app: finance-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
